from pathlib import Path
import pandas as pd

csv_path = Path("data/cache/realworld/metadata/graph_index_realworld.csv")

rows = [
    {
        "graph_id": "polblogs_gcc",
        "dataset": "polblogs",
        "variant": "gcc",
        "task": "node_classification",
        "label_name": "political_ideology",
        "edge_path": "polblogs/edges/polblogs_edges.csv",
        "label_path": "polblogs/labels/polblogs_labels.npy",
        "feature_path": "",
        "has_features": False,
        "feature_type": "none",
        "feature_dim": "",
        "n_nodes": 1222,
        "num_edges": 16714,
        "avg_degree": 27.355155482815057,
        "density": 0.022403894744320276,
        "num_connected_components": 1,
        "largest_cc_size": 1222,
        "largest_cc_fraction": 1.0,
        "num_classes": 2,
        "notes": "GCC used because full graph had many isolated/tiny components; no native features.",
        "esnr": 0.7070094910272954,
        "esnr_n_outliers": 2,
        "esnr_outlier_mass": 185.46447062350768,
        "esnr_converged": True,
        "esnr_iterations": 51,
    },
    {
        "graph_id": "lastfm_asia",
        "dataset": "lastfm_asia",
        "variant": "full",
        "task": "node_classification",
        "label_name": "country",
        "edge_path": "lastfm_asia/edges/lastfm_asia_edges.csv",
        "label_path": "lastfm_asia/labels/lastfm_asia_labels.npy",
        "feature_path": "lastfm_asia/features/lastfm_asia_features.npy",
        "has_features": True,
        "feature_type": "binary_artist_indicators",
        "feature_dim": 7842,
        "n_nodes": 7624,
        "num_edges": 27806,
        "avg_degree": 7.2943336831059815,
        "density": 0.0009568849118596328,
        "num_connected_components": 1,
        "largest_cc_size": 7624,
        "largest_cc_fraction": 1.0,
        "num_classes": 18,
        "notes": "Full graph used; includes native user-like artist preference features derived from raw JSON.",
        "esnr": 0.33308809380616355,
        "esnr_n_outliers": 13,
        "esnr_outlier_mass": 1305.9581184679455,
        "esnr_converged": True,
        "esnr_iterations": 313,
    },
    {
        "graph_id": "facebook_penn94_residence_min50_gcc",
        "dataset": "facebook100",
        "variant": "min50_gcc",
        "task": "node_classification",
        "label_name": "residence",
        "edge_path": "facebook_penn94/edges/facebook_penn94_edges.csv",
        "label_path": "facebook_penn94/labels/facebook_penn94_labels.npy",
        "feature_path": "facebook_penn94/features/facebook_penn94_features.npy",
        "has_features": True,
        "feature_type": "one_hot_metadata_excluding_residence",
        "feature_dim": 3089,
        "n_nodes": 12436,
        "num_edges": 251667,
        "avg_degree": 40.47394660662592,
        "density": 0.0032548409012163994,
        "num_connected_components": 1,
        "largest_cc_size": 12436,
        "largest_cc_fraction": 1.0,
        "num_classes": 75,
        "notes": "Used residence as label; dropped nodes with missing residence, excluded residence from features to avoid leakage, filtered classes with fewer than 50 members, then took GCC.",
        "esnr": 0.44754107509346636,
        "esnr_n_outliers": 73,
        "esnr_outlier_mass": 10039.860302653778,
        "esnr_converged": True,
        "esnr_iterations": 47,
    },
]

df = pd.DataFrame(rows)
df.to_csv(csv_path, index=False)
print(f"Updated {csv_path}")
print(df)